---
title: "Project-Group 24"
output:
  word_document: default
  html_notebook: default
  html_document:
    df_print: paged
---

```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
```


```{r}
library(readxl)
berdo <- read_excel("C:/Users/palash/Downloads/berdo-data-for-disclosure-calendar-year-2018 (1).xlsx")
head(berdo)
```

```{r}
# eliminate unuseful columns
clean_berdo <- berdo[, -c(1, 4, 9, 17, 19, 20, 21, 22, 23, 25)]
head(clean_berdo)
names(clean_berdo) <- c("reported", "proptype", "zip", "area", "EUI", "ESScore", "propuse", "yearbuilt", "GHGEmission", "GHGIntensity", "totalenergy", "electricity", "gas", "water", "covered")
clean_berdo$EUI <- as.numeric(clean_berdo$EUI)
clean_berdo$GHGEmission <- as.numeric(clean_berdo$GHGEmission)
clean_berdo$GHGIntensity <- as.numeric(clean_berdo$GHGIntensity)
clean_berdo$totalenergy <- as.numeric(clean_berdo$totalenergy)
clean_berdo$water <- as.numeric(clean_berdo$water)

```

```{r}
summary(clean_berdo)
```

```{r}

mean_berdo <- clean_berdo %>% 
  select(proptype, area, EUI, ESScore, GHGEmission, GHGIntensity, totalenergy, electricity, gas, water) %>% 
  group_by(proptype) %>% summarise_all(funs(mean), na.rm = TRUE)
view(mean_berdo)
clean_berdo <- clean_berdo[-c(14,27 ,43,59,88,99,126,139,141,244,260,283,288,357,408,426,431,460,464,478,479,482,491,507,512,528,581,623,627,647,660,661,662,676,681,685,693,694,759,837,848,861,866,872,945,965,973,1017,1045,1074,1113,1116,1128,1149,1168,1180,1214,1279,1285,1296,1300,1308,1347,1348,1351,1354,1357,1438,1440,1441,1442,1490,1491,1522,1536,1542,1567,1574,1584,1656,1709,1718,1739,1754),]

clean_berdo <- clean_berdo %>% filter(proptype != "Bar/Nightclub", 
                                      proptype != "Data Center", 
                                      proptype != "Ice/Curling Rink", 
                                      proptype != "Not Available", 
                                      proptype != "Race Track")

mean_berdo <- mean_berdo[-c(4, 8, 18,30,49),]   


```

```{r}
for(i in 1:length(clean_berdo$proptype)){
  for(j in 1:ncol(clean_berdo)){
    proptype1<-clean_berdo[i,2]
    if(is.na(clean_berdo[i,j])){
      clean_berdo[i,j] <- mean_berdo[which(mean_berdo$proptype == as.character(proptype1)), which(names(mean_berdo)  == names(clean_berdo[i,j]))]
    }
  }
}

# get rid of the ESSScore
clean_berdo <- clean_berdo %>% select(-ESScore)

clean_berdo <- na.omit(clean_berdo)
summary(clean_berdo)

#write.csv(clean_berdo, "C:/Users/palash/Documents/Desktop/clean_berdo.csv")
#trying to visualize the datset
library(ggplot2)
ggplot(clean_berdo,aes(y=water ,x=covered))+geom_boxplot()
#by plotting various box plots between covered and various other variables we found many outliers, so we need to remove those outliers to properly visualise the data ,for that we are using interquartile ranges and eliminating the values above 1.25IQR and 0.25 below IQR.
Q<-quantile(clean_berdo$GHGIntensity,probs = c(0.25,0.75,na.rm= FALSE))
iqr<- IQR(clean_berdo$GHGIntensity)
#Now that we know the IQR and the quantiles,we can find the cut-off ranges beyond which all data points are outliers.
up <-  Q[2]+1.5*iqr # Upper Range  
low<- Q[1]-1.5*iqr # Lower Range
#now we can simply extract the part of our dataset between the upper and lower ranges leaving out the outliers and we can further plot the boxplot and we will get better visualization .
eliminated_GHGIntensity<- subset(clean_berdo, clean_berdo$GHGIntensity > (Q[1] - 1.5*iqr) & clean_berdo$GHGIntensity < (Q[2]+1.5*iqr))
ggplot(eliminated_GHGIntensity,aes(y=GHGIntensity ,x=covered))+geom_boxplot()
#similarly we can try plotting for other functions as well 
ggplot(clean_berdo,aes(y=EUI,x=covered))+geom_boxplot() 
Q1<-quantile(eliminated_GHGIntensity$EUI,probs = c(0.25,0.75,na.rm= FALSE))
iqr1<- IQR(eliminated_GHGIntensity$EUI)
eliminated_EUI<- subset(eliminated_GHGIntensity, clean_berdo$EUI > (Q1[1] - 1.5*iqr1) & clean_berdo$EUI < (Q1[2]+1.5*iqr1))


```







